import type { Metadata } from 'next';
import { Poppins, Work_Sans } from 'next/font/google';
import './styles/globals.scss';
import { Header } from './components/layout/header';
import { Main } from './components/layout/main';
import { Footer } from './components/layout/footer';

export const metadata: Metadata = {
  title: 'Sempre visão',
  description: 'Generated by create next app'
};

const font = Work_Sans({
  subsets:["latin"],
  weight: ["300", "400", "500", "600" ,"700"],
  variable:"--work-sans"
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={font.className}>
        <Header />
        <Main>
          {children}
        </Main>
        <Footer />
      </body>
    </html>
  );
}
